#! /usr/local/bin/perl

while(<@ARGV>){
  if(-h){ &HELP; }
}

while(<>){

  unless(/Epoch/){

    $epoch++;

    # determine number of points in ascii file
    unless($gotit) { @data = split; $n = @data; $gotit = "yes"; }

    @data = split; $x = @data;
    if ($x != $n) {
      die "\a\a\nNumber of points is $x at epoch $epoch, rather than $n points!!!!\n\n";
    }

    print;
  }
}


sub HELP {

  print "\n\nA utility to convert an ascii file generated by the\n",
        "eeg2asc scan utility.  The scan-ascii utility prepares\n",
        "the data for tbcat.  It takes an *.asc file from stdin\n",
        "and creates a converted file on stout.\n\n",

        "eg: cat file.asc | scan-ascii | tbcat > file.tbl\n\n";

  exit;

}
